version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      timezone: Asia/Seoul
      interval: daily
      time: "20:00"
    open-pull-requests-limit: 10
    target-branch: develop
    labels:
      - dependencies
      - gradle
