version: "3.8"
services:
  postgres:
    container_name: witch_postgres
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: witch_endless
      POSTGRES_USER: witch
      POSTGRES_PASSWORD: witch
    volumes:
      - ./deploy/docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
