CREATE TABLE account (
  id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  nickname varchar(255) not null,
  email varchar(255) not null,
  unique_key varchar(255) not null,
  provider_type int4,
  role int4,
  firebase_uid varchar(255),
  gold numeric,
  jewel numeric,
  jwt_secret uuid not null,
  created_at timestamp NOT NULL,
  updated_at timestamp NOT NULL,
  CONSTRAINT account_pkey PRIMARY KEY (id)
);

CREATE TABLE device_token (
  id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  account_id int8,
  device_type int4 NOT NULL,
  value varchar(255) NOT NULL,
  created_at timestamp NOT NULL,
  updated_at timestamp NOT NULL
);

CREATE TABLE account_recent_device_tokens (
    account_id int8 not null,
    recent_device_tokens_id int8 not null
)
