CREATE TABLE account (
  id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  name varchar(255) not null,
  created_at timestamp NOT NULL,
  updated_at timestamp NOT NULL,
  CONSTRAINT account_pkey PRIMARY KEY (id)
);