# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Build the docker-compose stack
        run: docker-compose up -d
      - name: Sleep for 5 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '5s'
      - name: Grant setup
        run: chmod +x deploy/setup.sh
      - name: Setup
        run: ./deploy/setup.sh
      - name: Replace Action
        uses: datamonsters/replace-action@v2
        with:
          files: src/main/resources/application-secret.yml
          replacements: '${JWT_SECRET_KEY}=${{secrets.JWT_SECRET_KEY}},${JWT_EXPIRATION_TIME}=${{secrets.JWT_EXPIRATION_TIME}},${SERVICE_ACCOUNT_JSON}=${{secrets.SERVICE_ACCOUNT_JSON}},${FCM_DATABASE_URL}=${{secrets.FCM_DATABASE_URL}}'
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew flywayMigrate build -i
